package theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF904A49)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD8)
val secondaryLight = Color(0xFF775655)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD8)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF231919)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF231919)

val primaryLightMediumContrast = Color(0xFF6E2F30)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFAA5F5E)
val secondaryLightMediumContrast = Color(0xFF593B3A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF8F6C6B)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F7)
val onBackgroundLightMediumContrast = Color(0xFF231919)
val surfaceLightMediumContrast = Color(0xFFFFF8F7)
val onSurfaceLightMediumContrast = Color(0xFF231919)

val primaryLightHighContrast = Color(0xFF440F12)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF6E2F30)
val secondaryLightHighContrast = Color(0xFF341B1B)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF593B3A)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F7)
val onBackgroundLightHighContrast = Color(0xFF231919)
val surfaceLightHighContrast = Color(0xFFFFF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)

val primaryDark = Color(0xFF9CD49F)
val onPrimaryDark = Color(0xFF003913)
val primaryContainerDark = Color(0xFF1D5128)
val secondaryDark = Color(0xFFB8CCB5)
val onSecondaryDark = Color(0xFF243425)
val secondaryContainerDark = Color(0xFF3A4B3A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val backgroundDark = Color(0xFF101510)
val onBackgroundDark = Color(0xFFE0E4DB)
val surfaceDark = Color(0xFF101510)
val onSurfaceDark = Color(0xFFE0E4DB)

val primaryDarkMediumContrast = Color(0xFFA0D8A3)
val onPrimaryDarkMediumContrast = Color(0xFF001B06)
val primaryContainerDarkMediumContrast = Color(0xFF689D6D)
val secondaryDarkMediumContrast = Color(0xFFBCD0BA)
val onSecondaryDarkMediumContrast = Color(0xFF0A1A0C)
val secondaryContainerDarkMediumContrast = Color(0xFF839681)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val backgroundDarkMediumContrast = Color(0xFF101510)
val onBackgroundDarkMediumContrast = Color(0xFFE0E4DB)
val surfaceDarkMediumContrast = Color(0xFF101510)
val onSurfaceDarkMediumContrast = Color(0xFFF8FCF3)

val primaryDarkHighContrast = Color(0xFFF0FFEC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA0D8A3)
val secondaryDarkHighContrast = Color(0xFFF0FFEC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBCD0BA)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF101510)
val onBackgroundDarkHighContrast = Color(0xFFE0E4DB)
val surfaceDarkHighContrast = Color(0xFF101510)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)